repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-added-large-files
      args: ['--maxkb=100']
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace

- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
    - id: isort
      name: isort (python)
      args: ['--profile', 'black', '--filter-files']

- repo: https://github.com/psf/black
  rev: 23.1.0
  hooks:
    - id: black
      args: ['--line-length=88']

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.0.1
  hooks:
    - id: mypy
      pass_filenames: false
      args: ['lightkde', '--ignore-missing-imports']

- repo: https://github.com/pycqa/flake8
  rev: 6.0.0
  hooks:
    - id: flake8
      args: [
          '--max-line-length=88',
          '--select=E,F,W,C90,B,I',
          '--ignore=E203,W503',
          '--import-order-style=pycharm',
          '--application-import-names=lightkde, tests'
      ]
      additional_dependencies: [
          flake8-bugbear,
          flake8-tidy-imports,
          flake8-import-order
      ]
